### ISSUE TITLE
EditorMD问题

### ISSUE THREAD

**Issue by 1049759078** [LennonChin/BlogBackendProject#1]
请问EditorMD怎么集成的

**Comment by LennonChin** [comment]
你好，集成EditorMD的插件路径是`BlogBackendProject/extra_apps/pagedown/`，你可以这个插件；
另外可以在`BlogBackendProject/apps/article/adminx.py`这个文件里找到相关的集成代码。

我对EditorMD做了改进，因为图片用了七牛云托管，所以在上传文件时更改了上传流程。
