### ISSUE TITLE
访问受限

### ISSUE THREAD

**Issue by Gladysgong** [LennonChin/BlogBackendProject#2]
您好，我配置好输入127.0.0.1:8000后，提示访问受限，提示我输入密码。我创建了一个超级用户，输入那个密码也不正确啊。我想请问一下密码是在哪里配置的呢？

**Comment by LennonChin** [comment]
你好，有可能是因为我这边更新了加密的key，我晚上回去更新一下文档。

你可以尝试重新创建一个超级用户登录试试，登录地址是http://127.0.0.1:8000/xadmin/

另外如果还是无法登录的话，建议清空数据库重新做迁移。

**Comment by Gladysgong** [comment]
谢谢

**Comment by LennonChin** [comment]
你好，相关说明已做全面更新，请浏览Read Me文件。
