### ISSUE TITLE
启动服务访问网页时，提示list index out of range

### ISSUE THREAD

**Issue by itstyren** [LennonChin/BlogBackendProject#3]
你好，我在数据库迁移完成，设置好管理员用户后，启动服务访问xadmin和api页面均有此错误提示，请问应该如何解决。
![default](https://user-images.githubusercontent.com/26342068/48772030-1c925300-ecfe-11e8-9976-8489103fda14.png)

**Comment by itstyren** [comment]
我在private文件中，把邮件和七牛云字段都设置为1，但是应该不会影响吧？

**Comment by itstyren** [comment]
发现是由于初始表base_info中应该加入一条数据，我在表中加入数据之后就可以正常运行了，博主是否考虑可以把这一条加到说明文档呢？ （或者是我自己操作失误没有看到这一步？） @LennonChin

**Comment by LennonChin** [comment]
七牛云和邮件的字段设为1的话，发送邮件和上传图片就不能使用，可以把settings.py文件里的DEFAULT_FILE_STORAGE配置注释掉，就会走Django默认的文件存储，这样的话另外需要把private.py里的PRIVATE_MEDIA_URL_PREFIX设置成你的站点IP或域名，让图片可以顺利访问到。

数据库迁移初始化相关的问题，可能我也没有注意到，我找到时间排查一下。谢谢你的提醒。 @CyrusRenty
