### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:8080

### ISSUE THREAD

**Issue by Ray-SR** [LennonChin/BlogBackendProject#6]
博主你好，我下载了你的项目启动，依赖包都已安装，迁移也执行了，client-api.js和server-api.js也都配置了http://127.0.0.1:8000的地址，但是启动之后，浏览器显示`connect ECONNREFUSED 127.0.0.1:8080`，但是我后端是8000的端口啊，请问这里是什么问题呢？谢谢！

**Comment by LennonChin** [comment]
你好，可能是由于[前端工程Blog-Frontend-Project](https://github.com/LennonChin/Blog-Frontend-Project)后来做了SSR服务端渲染，开发模式下会默认在8080端口启动Node.js服务端渲染服务器，然后你本地有其他程序占用了8080端口，导致出现这个错误。在前端工程的：

- config/index.js
- server/routers/dev-ssr.js

这两个文件配置了8080端口。
你可以尝试把占用8080端口的程序停掉，或者修改这两个文件里的端口为其他端口，再重试看看。
